ssh_authorized_keys:
# use SSH public keys from my GitHub account
# syntax: "github:<accountname>"
# maps to https://github.com/<accountname>.keys
- "github:stephbu"

k3os:
  dns_nameservers:
  - 1.1.1.1
  ntp_servers:
  - 0.pool.ntp.org
  - 1.pool.ntp.org
  - 2.pool.ntp.org
  - 3.pool.ntp.org