apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
spec:
  replicas: 1
  template:
    metadata:
        name:code-server
    spec:
        hostNetwork:true
        containers:
        - name: code-server
          image: codercom/code-server:latest
          ports:
          - containerPort: 8080
