---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dns-storage
  namespace: stephbuorg
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dnsmasq-dns-storage
  namespace: stephbuorg
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: dns-storage
  local:
    path: /opt/dnsmasq
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: k3os.io/mode
          operator: In
          values:
          - local
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-dns-storage
  namespace: stephbuorg
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: dns-storage
  local:
    path: /opt/pihole
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: k3os.io/mode
          operator: In
          values:
          - local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-dns-storage-claim
  namespace: stephbuorg
spec:
  storageClassName: dns-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dnsmasq-dns-storage-claim
  namespace: stephbuorg
spec:
  storageClassName: dns-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: homedns
  namespace: stephbuorg
  labels:
    run: pihole
spec:
  containers:
  - name: pihole
    env:
    - name: TZ
      value: "America/Los_Angeles"
    - name: WEBPASSWORD
      valueFrom:
        secretKeyRef:
          name: pihole-secrets
          key: password
    image: pihole/pihole:latest
    ports:
    - name: dnsoverhttp
      containerPort: 53
      protocol: TCP
    - name: dnsoverudp
      containerPort: 53
      protocol: UDP
    - name: dnsmasq
      containerPort: 67
      protocol: UDP
    - name: adminwebhttp
      containerPort: 80
      protocol: TCP
    - name: adminwebhttps
      containerPort: 443
      protocol: TCP      
    imagePullPolicy: Always
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "SYS_TIME"]
    volumeMounts:
    - name: pihole-dns-storage
      mountPath: /etc/pihole/
    - name: dnsmasq-dns-storage
      mountPath: /etc/dnsmasq.d/
  volumes:
  - name: pihole-dns-storage
    persistentVolumeClaim:
      claimName: pihole-dns-storage-claim
  - name: dnsmasq-dns-storage
    persistentVolumeClaim:
      claimName: dnsmasq-dns-storage-claim  
  dnsPolicy: ClusterFirstWithHostNet
  priority: 0
  restartPolicy: OnFailure
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns
  namespace: stephbuorg
  labels:
    run: pihole
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 53
    targetPort: 53
    protocol: UDP
    name: dnsoverudp
  selector:
    run: pihole
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-adminweb
  labels:
    run: pihole
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 8081
    targetPort: 80
    protocol: TCP
    name: adminwebhttp
  selector:
    run: pihole
