apiVersion: v1
kind: PersistentVolume
metadata:
  name: codeserver-project-storage
  namespace: stephbuorg
  labels:
    app: codeserver
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /opt/codeserver
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: k3os.io/mode
          operator: In
          values:
          - local