apiVersion: v1
kind: PersistentVolume
metadata:
  name: codeserver-project-storage
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /opt/codeserver