apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codeserver-project-storage
  namespace: stephbuorg
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      asset: code