apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codeserver-project-storage
  namespace: stephbuorg
spec:
  storageClassName: code-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi